name: Deploy to Azure Web App

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: akddynamicwebapp
      CONTAINER_REGISTRY: akddynamicwebapp
      RESOURCE_GROUP: DynamicWebApp
      WEB_APP_NAME: andreaskristiandahlgren
      PERSONAL_DOMAIN: andreaskristiandahlgren
      LOCATION: swedencentral

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Register Microsoft.Web provider
      run: az provider register --namespace Microsoft.Web

    - name: Register Microsoft.App provider
      run: az provider register --namespace Microsoft.App --wait

    - name: Login to ACR
      uses: docker/login-action@v2
      with:
        registry: ${{ env.CONTAINER_REGISTRY }}.azurecr.io
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - name: Build and Push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: 'Dockerfile'
        push: true
        tags: |
          ${{ env.CONTAINER_REGISTRY }}.azurecr.io/${{ env.IMAGE_NAME }}:${{ github.run_id }}
          ${{ env.CONTAINER_REGISTRY }}.azurecr.io/${{ env.IMAGE_NAME }}:latest
        registry: ${{ env.CONTAINER_REGISTRY }}.azurecr.io

    - name: Deploy to Azure Web App for Containers - Personal Named Domain
      run: |
        az webapp config container set \
          --name ${{ env.WEB_APP_NAME }} \
          --resource-group ${{ env.RESOURCE_GROUP }} \
          --container-image-name ${{ env.CONTAINER_REGISTRY }}.azurecr.io/${{ env.IMAGE_NAME }}:latest
